# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ~/Desktop/test-api/test-api/mongo_data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      MR_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    links:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
